on:
  push:
    branches:
      - dev

name: Tests
jobs:
  test:
    name: glassyPDM Rust unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run test with cli
          working-directory: src-tauri
          run: cargo test