on:
  push:
    branches:
      - dev

name: Tests
jobs:
  test:
    name: glassyPDM Rust unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        working-directory: ./src-tauri
        with:
          command: test